'use client';

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Layers, MessageSquare, FileText, ArrowLeft, ArrowUpRight } from 'lucide-react';
import Link from 'next/link';
import { Container } from '@/components/layout';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Text } from '@/components/ui/Text';
import { TracklyMockup, ChatVideoMockup, ResumeMockup } from '@/components/features/Projects';

const categories = ['All', 'Full Stack', 'Real-time', 'AI'] as const;
type Category = (typeof categories)[number];

interface Project {
  title: string;
  categoryName: string;
  filterCategory: Category;
  description: string;
  features: string[];
  tech: string[];
  liveUrl: string;
  githubUrl: string;
  mockup: React.ReactNode;
  icon: React.ReactNode;
  slug: string;
}

const projectsData: Project[] = [
  {
    title: 'Trackly',
    categoryName: 'Productivity SaaS',
    filterCategory: 'Full Stack',
    description:
      'Designed a collaborative workspace featuring optimistic drag-and-drop Kanban states, JWT auth guards, and team workspaces with role-based permissions (RBAC) to handle active issue tracking.',
    features: [
      'Interactive Kanban board with drag-and-drop mechanics',
      'JWT Authentication & OAuth integrations',
      'Role-based permissions (Owner, Member, Observer)',
      'Real-time updates for team collaboration',
    ],
    tech: ['React', 'Node.js', 'MongoDB', 'Express', 'JWT', 'REST API'],
    liveUrl: 'https://trackly-psi.vercel.app',
    githubUrl: 'https://github.com/amanshishodia/trackly',
    mockup: <TracklyMockup />,
    icon: <Layers className="h-5 w-5 text-blue-500" />,
    slug: 'trackly',
  },
  {
    title: 'Streamify',
    categoryName: 'Real-time Communication',
    filterCategory: 'Real-time',
    description:
      'Constructed a low-latency communication system integrating WebRTC peer feeds (Stream API) and Socket.io state reconciliations. Implemented optimistic updates for instant UI messaging feedback.',
    features: [
      'Low-latency WebRTC group video and audio calls (Stream API)',
      'Persistent chat channels with custom socket connections',
      'Optimistic UI state updates for sub-100ms response feel',
      'Fully responsive, mobile-first dashboard structure',
    ],
    tech: ['React', 'Node.js', 'Socket.io', 'Stream API', 'WebRTC', 'Tailwind'],
    liveUrl: 'https://streamify-uv86.onrender.com/',
    githubUrl: 'https://github.com/amanshishodia/chat-video-app',
    mockup: <ChatVideoMockup />,
    icon: <MessageSquare className="h-5 w-5 text-indigo-500" />,
    slug: 'chat-video',
  },
  {
    title: 'Resume Analyzer',
    categoryName: 'AI Tool',
    filterCategory: 'AI',
    description:
      'Built an ATS profiling engine scanning PDF formats, parsing tokenized layout keyword weights, and utilizing PuterJS cloud nodes to calculate action metrics.',
    features: [
      'Circular progress meters for overall ATS performance',
      'Dynamic keyword mapping & density tracking',
      'PDF parser & cloud extraction tools via PuterJS',
      'Instantly actionable feedback logs generated by AI',
    ],
    tech: ['React', 'TypeScript', 'PuterJS', 'ATS Parsing', 'AI Integration'],
    liveUrl: 'https://resume-analyzer-one-beige.vercel.app/',
    githubUrl: 'https://github.com/amanshishodia/resume-analyzer',
    mockup: <ResumeMockup />,
    icon: <FileText className="h-5 w-5 text-emerald-500" />,
    slug: 'resume-analyzer',
  },
];

export default function ProjectsPage() {
  const [activeCategory, setActiveCategory] = useState<Category>('All');

  const filteredProjects = projectsData.filter((p) => {
    if (activeCategory === 'All') return true;
    return p.filterCategory === activeCategory;
  });

  return (
    <div className="bg-background relative min-h-screen pb-20">
      {/* Subtle top spotlight glow */}
      <div className="absolute top-0 left-1/2 h-[350px] w-[500px] -translate-x-1/2 rounded-full bg-blue-500/5 blur-[100px] pointer-events-none" />

      <Container className="pt-12 md:pt-20">
        {/* Back Link */}
        <Link
          href="/"
          className="group text-muted-foreground hover:text-foreground mb-8 inline-flex items-center space-x-2 text-xs font-mono transition-colors"
        >
          <ArrowLeft className="h-3.5 w-3.5 transition-transform group-hover:-translate-x-0.5" />
          <span>BACK TO HOME</span>
        </Link>

        {/* Page Header */}
        <div className="mb-12 flex flex-col space-y-4">
          <Text
            as="span"
            family="mono"
            size="xs"
            color="accent"
            weight="bold"
            className="tracking-widest uppercase"
          >
            engineering chronicle
          </Text>
          <Text as="h1" size="4xl" weight="extrabold" className="tracking-tight">
            Projects.
          </Text>
          <Text color="muted" size="base" className="max-w-[34rem] text-sm sm:text-base leading-relaxed">
            A comprehensive list of products and developer utilities built to solve specific technical
            problems. Focus on API structures, clean states, and modern UI.
          </Text>
        </div>

        {/* Filter Tabs */}
        <div className="border-border/60 mb-10 flex flex-wrap gap-1.5 border-b pb-4">
          {categories.map((cat) => {
            const isSelected = activeCategory === cat;
            return (
              <button
                key={cat}
                onClick={() => setActiveCategory(cat)}
                className={`relative px-4 py-1.5 font-mono text-xs font-medium transition-colors rounded-md focus:outline-none ${
                  isSelected ? 'text-foreground' : 'text-muted-foreground hover:text-foreground'
                }`}
              >
                {cat}
                {isSelected && (
                  <motion.div
                    layoutId="activeFilter"
                    className="border-border bg-secondary absolute inset-0 -z-10 rounded-md border shadow-sm"
                    transition={{ type: 'spring', stiffness: 380, damping: 30 }}
                  />
                )}
              </button>
            );
          })}
        </div>

        {/* Grid Container */}
        <motion.div layout className="grid gap-8 grid-cols-1">
          <AnimatePresence mode="popLayout">
            {filteredProjects.map((project) => (
              <motion.div
                key={project.title}
                layout
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.98 }}
                transition={{ duration: 0.25 }}
              >
                <Card variant="interactive" className="bg-[#111111] overflow-hidden" style={{ transformStyle: 'preserve-3d' }}>
                  <div className="grid grid-cols-1 md:grid-cols-12" style={{ transformStyle: 'preserve-3d' }}>
                    {/* Visual mockup sidebar */}
                    <div 
                      className="border-border relative flex min-h-[220px] items-center justify-center border-b bg-[#09090b] p-6 md:col-span-5 md:border-r md:border-b-0"
                      style={{ transform: 'translateZ(20px)', transformStyle: 'preserve-3d' }}
                    >
                      <div className="absolute inset-0 bg-[radial-gradient(#1e1b4b_1px,transparent_1px)] bg-[size:16px_16px] opacity-15" />
                      <div className="relative z-10 w-full max-w-[280px]" style={{ transform: 'translateZ(10px)' }}>
                        {project.mockup}
                      </div>
                    </div>

                    {/* Detailed info panel */}
                    <div 
                      className="flex flex-col justify-between p-6 sm:p-8 md:col-span-7"
                      style={{ transform: 'translateZ(15px)', transformStyle: 'preserve-3d' }}
                    >
                      <div className="space-y-6">
                        {/* Title header */}
                        <div className="flex items-start justify-between" style={{ transform: 'translateZ(5px)' }}>
                          <div className="space-y-1">
                            <Text family="mono" size="xs" color="muted">
                              {project.categoryName}
                            </Text>
                            <div className="flex items-center space-x-2">
                              {project.icon}
                              <Text as="h3" size="xl" weight="bold">
                                {project.title}
                              </Text>
                            </div>
                          </div>
                        </div>

                        {/* Description */}
                        <Text 
                          size="sm" 
                          color="muted" 
                          className="leading-relaxed"
                          style={{ transform: 'translateZ(2px)' }}
                        >
                          {project.description}
                        </Text>

                        {/* Features Checklist */}
                        <div className="space-y-2" style={{ transform: 'translateZ(4px)' }}>
                          <Text family="mono" size="xs" color="primary" weight="semibold">
                            KEY MODULES & IMPLEMENTATIONS:
                          </Text>
                          <ul className="grid gap-1.5 grid-cols-1 sm:grid-cols-2">
                            {project.features.map((feature) => (
                              <li key={feature} className="flex items-start space-x-2 text-xs text-zinc-400">
                                <span className="mt-1 h-1 w-1.5 rounded-full bg-blue-500 flex-shrink-0" />
                                <span>{feature}</span>
                              </li>
                            ))}
                          </ul>
                        </div>

                        {/* Tech stack items */}
                        <div className="flex flex-wrap gap-1.5 pt-2" style={{ transform: 'translateZ(3px)' }}>
                          {project.tech.map((t) => (
                            <span
                              key={t}
                              className="border-border rounded border bg-[#161618] px-2.5 py-0.5 font-mono text-[10px] font-medium text-zinc-400"
                            >
                              {t}
                            </span>
                          ))}
                        </div>
                      </div>

                      {/* Actions */}
                      <div 
                        className="border-border/40 mt-8 flex flex-wrap gap-3 border-t pt-6"
                        style={{ transform: 'translateZ(8px)' }}
                      >
                        <Button
                          variant="accent"
                          size="sm"
                          href={`/projects/${project.slug}`}
                          rightIcon={<ArrowUpRight className="h-3.5 w-3.5" />}
                          className="w-full sm:w-auto text-xs"
                        >
                          Read Case Study
                        </Button>
                        <Button
                          variant="secondary"
                          size="sm"
                          href={project.liveUrl}
                          className="w-full sm:w-auto text-xs"
                        >
                          Demo
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          href={project.githubUrl}
                          className="w-full sm:w-auto text-xs"
                        >
                          Source Code
                        </Button>
                      </div>
                    </div>
                  </div>
                </Card>
              </motion.div>
            ))}
          </AnimatePresence>
        </motion.div>
      </Container>
    </div>
  );
}
